### ISSUE TITLE
Test results Review: Few apps failing consistently 

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci#103]
Following are some of the apps that are failing consistently for the last 2 weeks 

- [ ] All the 19X-reactlog apps - changes in the reactlog graph -- Barret
- [x] 081- widgets-gallery - Madhu - Height adjusted (not fixed)
- [x] 060-retirement-simulation - Madhu - Combination of slider tick changes and also few builds failing on plot section - width adjusted (not fixed)
- [x] 021-selectize-plot (linux 3.6 only) -- Madhu - height diffs - Height adjusted in the test
- [ ] 114-modal-dialog - cursor in the selectinput  box shown as a difference -- Barret
- [ ] 303-bslib-html-template - cursor in the selectInput box shown as a difference -- Barret
- [x] 082-word-cloud (linux 3.6 only) -- Madhu (height diffs - current snaps height accepted as it is)
- [x] 118-high-charter-births (windows 3.6 and linux 3.6) -- Madhu (height diffs - current snaps accepted as it is)
- [x] 150-network-D3-sankey  -- (windows 3.6, linux 3.6 and windows 3.5) -- Madhu (height diffs - current snaps accepted as is)
- [x] 151-reactr-input --(linux 3.6, windows 3.5, windows 3.6) -- Madhu (height diffs - current snaps accepted as is)
- [x] 216-quosures --- (linux 3.6, windows 3.6) Madhu to double check (width adjusted in the test) (not fixed)
- [ ] 016-knitr-pdf, 010-download, 039-download-file, 112-generate-report - Tests failing on all builds since May 26. Download fa icon subtle diffs (rejected)

More details at https://docs.google.com/document/d/1WxdQT30hdVCIWBzPwKGT1pw8xWin6lQlbjtDUL0NIcI/edit#

Few examples:

**19X-reactlog-apps**

<img width="777" alt="Screen Shot 2022-05-24 at 10 25 12 AM" src="https://user-images.githubusercontent.com/5369655/170096338-b5f876b1-e615-4124-91d4-2067674df309.png">
<img width="913" alt="Screen Shot 2022-05-24 at 10 25 32 AM" src="https://user-images.githubusercontent.com/5369655/170096349-293bce46-7565-4bb4-886b-190e5d9cda29.png">

**081-widgets-gallery**

<img width="577" alt="Screen Shot 2022-05-24 at 1 25 07 PM" src="https://user-images.githubusercontent.com/5369655/170125761-3e92ec47-a06e-433a-acf9-375cd6def894.png">
<img width="570" alt="Screen Shot 2022-05-24 at 1 25 23 PM" src="https://user-images.githubusercontent.com/5369655/170125781-2120330e-cee7-431e-ac9e-978d3171540b.png">

**060-retirement-simulation**
<img width="639" alt="Screen Shot 2022-05-24 at 1 27 11 PM" src="https://user-images.githubusercontent.com/5369655/170126280-531a4b94-ac23-4c7d-86b6-b3a47a232873.png">
<img width="667" alt="Screen Shot 2022-05-24 at 1 28 10 PM" src="https://user-images.githubusercontent.com/5369655/170126313-cc3d0840-8130-4683-8b58-8a6ce1d0c5db.png">

**114-modal-dialog** and **303-bslib-html-template**
<img width="1263" alt="Screen Shot 2022-05-24 at 5 45 15 PM" src="https://user-images.githubusercontent.com/5369655/170154839-ff65f69d-c21d-448c-a156-a01279de214b.png">
<img width="719" alt="Screen Shot 2022-05-24 at 5 45 22 PM" src="https://user-images.githubusercontent.com/5369655/170154846-9df2deed-6bad-4c74-b4d1-04d38f96009b.png">
<img width="1244" alt="Screen Shot 2022-05-24 at 5 45 55 PM" src="https://user-images.githubusercontent.com/5369655/170154848-fcc1d4ed-3cf7-4769-9428-9bfb8cca53e9.png">
<img width="727" alt="Screen Shot 2022-05-24 at 5 45 33 PM" src="https://user-images.githubusercontent.com/5369655/170154849-100a454c-a3a7-48e2-8d1b-79a16224383d.png">

**016-knitr-pdf** and **010-download**
<img width="1232" alt="Screen Shot 2022-06-01 at 3 03 13 PM" src="https://user-images.githubusercontent.com/5369655/171509433-b5300015-c7a9-45f5-b646-200e212d23a2.png">

<img width="1064" alt="Screen Shot 2022-06-01 at 3 04 34 PM" src="https://user-images.githubusercontent.com/5369655/171509712-378f9146-b362-48b2-ba08-4a6897153732.png">

**Comment by schloerke** [comment]
114 and 303 should be fixed in main. The snapshots will need to be updated.

I'm having a hard time fixing 19x reactlog apps. I can reprex the inconsistent behavior, but I can not get the graph to stay put with the same CSS values.

I'd like to have the apps NOT be manual if we can help it. These are the only apps that I am aware of that are testing the UI of reactlog. 😞

**Comment by MadhulikaTanuboddi** [comment]
> The 19X reactlog apps are trying to be fixed in #106.
> 
> The image count has been reduced, but there are still errors while drawing the `canvas` tags. The font looks like it is flip flopping between bold and regular font weight. I don't know if this is a `{reactlog}` issue or a `{chromote}` issue. The flip flopping is reproducible locally.

Thank you @schloerke for the details. FWIW, I did not the font bold vs regular issue on few other apps too and they are definitely not consistent. Sometimes, its the font size or style. An example below

https://rstudio.slack.com/files/UKQDUE9T2/F03JABK84JV/screenshare_-_2022-06-01_4_33_29_pm.webm
> 
> Hopefully it'll get resolved. Otherwise, we should remove the screenshot tests and make the apps manual apps.

**Comment by schloerke** [comment]
The reactlog apps have had their screenshots removed and I added one app for manual testing in https://github.com/rstudio/shinycoreci/pull/108

**Comment by schloerke** [comment]
Closing as these apps have been addressed over the past few months. Not descriptive, but on 2023/02/09 only 145, 150, 154, and 185 were failing.
