### ISSUE TITLE
Slider app test failures

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci#115]
Since 06/08/2022 nightly run, some of the slider apps started failing.

It looks like this is mostly with slider with **Decimal ticks**. Below is an example. Notice that in the original and expected snapshot, the  Decimal slider is supposed to show "0.3",  but the new snapshots show "0".

<img width="1334" alt="Screen Shot 2022-06-15 at 8 13 12 AM" src="https://user-images.githubusercontent.com/5369655/173863297-c2631063-2d48-4a64-ae3e-75c3ee9f68e4.png">

Apps impacted:

1. `005-sliders`
2. `026-shiny-inline`
3. `047-image-output`
4. `054-nvd3-line-chart-output`

https://user-images.githubusercontent.com/5369655/173863665-114d4c16-53eb-426d-93ae-889ffff9bdf1.mp4

When I manually tested these apps, I am able to use the sliders properly and as expected. So, this seems to be a shinytest2/chromote issue. I am wondering if this is anyway related to Barret's changes from "shinytest2" (from June 8).

https://github.com/rstudio/shinytest2/commits/main

**Comment by wch** [comment]
If this is the 005-sliders app, the starting value is supposed to be 0.5, not 0.3 or 0.
https://github.com/rstudio/shinycoreci-apps/blob/53dc99d/apps/005-sliders/app.R#L24-L26

**Comment by MadhulikaTanuboddi** [comment]
Just to add more info, the tests started failing from June 9

<img width="1589" alt="Screen Shot 2022-06-15 at 9 50 01 AM" src="https://user-images.githubusercontent.com/5369655/173882599-86ea945c-89e8-4d28-a1ac-2c8968d8ced0.png">

**Comment by wch** [comment]
Should be fixed by https://github.com/rstudio/shinytest2/pull/229.

**Comment by MadhulikaTanuboddi** [comment]
> Should be fixed by [rstudio/shinytest2#229](https://github.com/rstudio/shinytest2/pull/229).

thank you!

**Comment by MadhulikaTanuboddi** [comment]
fixed from the 06/16 test run -> https://rstudio.github.io/shinycoreci/results/2022/06/16/
