### ISSUE TITLE
060: shinytest2 appconsistent failures due to png width and height changes

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci#116]
This app has been failing consistently over the last few builds (even after double checking and accepting the new pngs as of 06/17) (Note: this app has been failing on and off since the time we transitioned to shinytest2).

Upon reviewing the changes with Winston last week and as of today too, we noticed that the pngs width and heights are constantly changing that is resulting in pixel shifts with sliders and plots though we are setting a constant width and height in the shinytest2 script https://github.com/rstudio/shinycoreci/blob/main/inst/apps/060-retirement-simulation/tests/testthat/test-mytest.R#L5

I will keep an eye on this test and check with the team what would be a better solution.

https://user-images.githubusercontent.com/5369655/175428715-4ebfe26e-1d76-4eb8-8f9b-30d0779a93f9.mp4

**Comment by schloerke** [comment]
Seems to be fixed. Resolving
