### ISSUE TITLE
R3.5: Tests not running on all the builds

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci#125]
In our GHA runs, the tests have not been running at all on all the OSes (Mac, Windows and Linux) due to some circular dependency issues with package installation (or atleast on Mac even if the installation is good, the tests are timing out)

**Ubuntu** - https://github.com/rstudio/shinycoreci/runs/7086259749?check_suite_focus=true#step:12:1452

<img width="1270" alt="Screen Shot 2022-06-28 at 10 26 20 AM" src="https://user-images.githubusercontent.com/5369655/176245128-15207e05-2b6d-45ee-91ce-fc65e3df920c.png">

**Windows** - https://github.com/rstudio/shinycoreci/runs/7088646549?check_suite_focus=true#step:12:442

<img width="1248" alt="Screen Shot 2022-06-28 at 10 27 27 AM" src="https://user-images.githubusercontent.com/5369655/176245345-bc1b70cf-0ed7-43ed-8105-1cb31d51c8e7.png">

**Mac** - https://github.com/rstudio/shinycoreci/runs/7086285791?check_suite_focus=true#step:14:139
<img width="971" alt="Screen Shot 2022-06-28 at 10 29 00 AM" src="https://user-images.githubusercontent.com/5369655/176245779-29df8514-07f0-4564-93c4-8bff795f6a21.png">

**Comment by schloerke** [comment]
The easiest action will be to wait for the next version of R, dropping support for R 3.5.  Leaving open until then

**Comment by schloerke** [comment]
Closing via #163 

🔥 R 3.5 🔥
