### ISSUE TITLE
Make sure shinythemes can install from the main exact deps installation command

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/shinycoreci#57]
test_in_sso/ssp: update docker image to include "shinythemes" installation

Ref: 
<img width="1152" alt="shinythemes_sso_docker_testing" src="https://user-images.githubusercontent.com/5369655/104642689-17bc5600-5660-11eb-8a89-45eefc00b664.png">

**Comment by schloerke** [comment]
app works. closing
